package(default_visibility = ["//:internal"])

licenses(["notice"])

exports_files(
    ["base.swig"],
    visibility = ["//:internal"],
)

filegroup(
    name = "swig_includes",
    srcs = glob(["*.swig"]),
)
