# GCE-compatible alternatives for GRPC
package(default_visibility = ["//:internal"])

licenses(["notice"])

cc_library(
    name = "grpc",
    hdrs = ["grpc.h"],
    deps = ["@com_github_grpc_grpc//:grpc++"],
)
