// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/quickstore_microservice/proto/quickstore.proto

package mako_internal_quickstore_microservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	quickstore_go_proto "github.com/google/mako/quickstore/quickstore_go_proto"
	mako_go_proto "github.com/google/mako/spec/proto/mako_go_proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreInput struct {
	QuickstoreInput      *quickstore_go_proto.QuickstoreInput `protobuf:"bytes,1,opt,name=quickstore_input,json=quickstoreInput" json:"quickstore_input,omitempty"`
	SamplePoints         []*mako_go_proto.SamplePoint         `protobuf:"bytes,2,rep,name=sample_points,json=samplePoints" json:"sample_points,omitempty"`
	SampleErrors         []*mako_go_proto.SampleError         `protobuf:"bytes,3,rep,name=sample_errors,json=sampleErrors" json:"sample_errors,omitempty"`
	RunAggregates        []*mako_go_proto.KeyedValue          `protobuf:"bytes,4,rep,name=run_aggregates,json=runAggregates" json:"run_aggregates,omitempty"`
	AggregateValueKeys   []string                             `protobuf:"bytes,5,rep,name=aggregate_value_keys,json=aggregateValueKeys" json:"aggregate_value_keys,omitempty"`
	AggregateValueTypes  []string                             `protobuf:"bytes,6,rep,name=aggregate_value_types,json=aggregateValueTypes" json:"aggregate_value_types,omitempty"`
	AggregateValueValues []float64                            `protobuf:"fixed64,7,rep,name=aggregate_value_values,json=aggregateValueValues" json:"aggregate_value_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *StoreInput) Reset()         { *m = StoreInput{} }
func (m *StoreInput) String() string { return proto.CompactTextString(m) }
func (*StoreInput) ProtoMessage()    {}
func (*StoreInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80613028ee3e5eb0, []int{0}
}

func (m *StoreInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreInput.Unmarshal(m, b)
}
func (m *StoreInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreInput.Marshal(b, m, deterministic)
}
func (m *StoreInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreInput.Merge(m, src)
}
func (m *StoreInput) XXX_Size() int {
	return xxx_messageInfo_StoreInput.Size(m)
}
func (m *StoreInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreInput.DiscardUnknown(m)
}

var xxx_messageInfo_StoreInput proto.InternalMessageInfo

func (m *StoreInput) GetQuickstoreInput() *quickstore_go_proto.QuickstoreInput {
	if m != nil {
		return m.QuickstoreInput
	}
	return nil
}

func (m *StoreInput) GetSamplePoints() []*mako_go_proto.SamplePoint {
	if m != nil {
		return m.SamplePoints
	}
	return nil
}

func (m *StoreInput) GetSampleErrors() []*mako_go_proto.SampleError {
	if m != nil {
		return m.SampleErrors
	}
	return nil
}

func (m *StoreInput) GetRunAggregates() []*mako_go_proto.KeyedValue {
	if m != nil {
		return m.RunAggregates
	}
	return nil
}

func (m *StoreInput) GetAggregateValueKeys() []string {
	if m != nil {
		return m.AggregateValueKeys
	}
	return nil
}

func (m *StoreInput) GetAggregateValueTypes() []string {
	if m != nil {
		return m.AggregateValueTypes
	}
	return nil
}

func (m *StoreInput) GetAggregateValueValues() []float64 {
	if m != nil {
		return m.AggregateValueValues
	}
	return nil
}

type StoreOutput struct {
	QuickstoreOutput     *quickstore_go_proto.QuickstoreOutput `protobuf:"bytes,1,opt,name=quickstore_output,json=quickstoreOutput" json:"quickstore_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *StoreOutput) Reset()         { *m = StoreOutput{} }
func (m *StoreOutput) String() string { return proto.CompactTextString(m) }
func (*StoreOutput) ProtoMessage()    {}
func (*StoreOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80613028ee3e5eb0, []int{1}
}

func (m *StoreOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreOutput.Unmarshal(m, b)
}
func (m *StoreOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreOutput.Marshal(b, m, deterministic)
}
func (m *StoreOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreOutput.Merge(m, src)
}
func (m *StoreOutput) XXX_Size() int {
	return xxx_messageInfo_StoreOutput.Size(m)
}
func (m *StoreOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StoreOutput proto.InternalMessageInfo

func (m *StoreOutput) GetQuickstoreOutput() *quickstore_go_proto.QuickstoreOutput {
	if m != nil {
		return m.QuickstoreOutput
	}
	return nil
}

type ShutdownInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownInput) Reset()         { *m = ShutdownInput{} }
func (m *ShutdownInput) String() string { return proto.CompactTextString(m) }
func (*ShutdownInput) ProtoMessage()    {}
func (*ShutdownInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80613028ee3e5eb0, []int{2}
}

func (m *ShutdownInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownInput.Unmarshal(m, b)
}
func (m *ShutdownInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownInput.Marshal(b, m, deterministic)
}
func (m *ShutdownInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownInput.Merge(m, src)
}
func (m *ShutdownInput) XXX_Size() int {
	return xxx_messageInfo_ShutdownInput.Size(m)
}
func (m *ShutdownInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownInput.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownInput proto.InternalMessageInfo

type ShutdownOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownOutput) Reset()         { *m = ShutdownOutput{} }
func (m *ShutdownOutput) String() string { return proto.CompactTextString(m) }
func (*ShutdownOutput) ProtoMessage()    {}
func (*ShutdownOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_80613028ee3e5eb0, []int{3}
}

func (m *ShutdownOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownOutput.Unmarshal(m, b)
}
func (m *ShutdownOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownOutput.Marshal(b, m, deterministic)
}
func (m *ShutdownOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownOutput.Merge(m, src)
}
func (m *ShutdownOutput) XXX_Size() int {
	return xxx_messageInfo_ShutdownOutput.Size(m)
}
func (m *ShutdownOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StoreInput)(nil), "mako.internal.quickstore_microservice.StoreInput")
	proto.RegisterType((*StoreOutput)(nil), "mako.internal.quickstore_microservice.StoreOutput")
	proto.RegisterType((*ShutdownInput)(nil), "mako.internal.quickstore_microservice.ShutdownInput")
	proto.RegisterType((*ShutdownOutput)(nil), "mako.internal.quickstore_microservice.ShutdownOutput")
}

func init() {
	proto.RegisterFile("internal/quickstore_microservice/proto/quickstore.proto", fileDescriptor_80613028ee3e5eb0)
}

var fileDescriptor_80613028ee3e5eb0 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0xae, 0x93, 0x40,
	0x14, 0xc6, 0xa5, 0x58, 0x8d, 0xa7, 0xf6, 0xdf, 0xd8, 0x1a, 0x82, 0x1b, 0x24, 0x31, 0x61, 0x45,
	0x95, 0x54, 0xbb, 0x76, 0xe1, 0xc2, 0x34, 0xfe, 0xa3, 0xc6, 0x9d, 0x21, 0x84, 0x4e, 0x2a, 0x69,
	0xcb, 0xd0, 0x99, 0xa1, 0x86, 0x07, 0xb8, 0xf7, 0x31, 0xee, 0xb3, 0xde, 0x70, 0x28, 0x30, 0x6d,
	0x73, 0x6f, 0xda, 0xcd, 0x64, 0xe6, 0x7c, 0xe7, 0xf7, 0x71, 0x98, 0x6f, 0x60, 0x16, 0x27, 0x92,
	0xf2, 0x24, 0xdc, 0x4c, 0x76, 0x59, 0x1c, 0xad, 0x85, 0x64, 0x9c, 0x06, 0xdb, 0x38, 0xe2, 0x4c,
	0x50, 0xbe, 0x8f, 0x23, 0x3a, 0x49, 0x39, 0x93, 0x4c, 0x51, 0x5d, 0x2c, 0x90, 0x77, 0xdb, 0x70,
	0xcd, 0xdc, 0x8a, 0x76, 0x1f, 0xa0, 0xcd, 0x37, 0x8d, 0x70, 0xe6, 0x61, 0x8e, 0x45, 0x4a, 0xa3,
	0xc3, 0x07, 0xd0, 0x0e, 0xb7, 0xf6, 0x9d, 0x0e, 0xb0, 0x28, 0xda, 0xbe, 0x26, 0x69, 0x26, 0xc9,
	0x1c, 0x06, 0x8a, 0x7b, 0x5c, 0xd4, 0x0c, 0xcd, 0xd2, 0x9c, 0x8e, 0x67, 0xb9, 0x48, 0x29, 0xbe,
	0xbf, 0xea, 0x2d, 0xb2, 0x7e, 0x7f, 0x77, 0x5c, 0x20, 0x9f, 0xa0, 0x2b, 0xc2, 0x6d, 0xba, 0xa1,
	0x41, 0xca, 0xe2, 0x44, 0x0a, 0xa3, 0x65, 0xe9, 0x4e, 0xc7, 0x1b, 0x96, 0x4e, 0x0b, 0x94, 0x7e,
	0x16, 0x8a, 0xff, 0x52, 0x34, 0x07, 0xa1, 0x70, 0x94, 0x73, 0xc6, 0x85, 0xa1, 0x9f, 0x73, 0x5f,
	0x0a, 0xa5, 0xe2, 0xf0, 0x20, 0xc8, 0x0c, 0x7a, 0x3c, 0x4b, 0x82, 0x70, 0xb5, 0xe2, 0x74, 0x15,
	0x4a, 0x2a, 0x8c, 0xa7, 0x08, 0x0e, 0x4a, 0x70, 0x4e, 0x73, 0xba, 0xfc, 0x13, 0x6e, 0x32, 0xea,
	0x77, 0x79, 0x96, 0x7c, 0xae, 0xdb, 0xc8, 0x7b, 0x18, 0xd5, 0x50, 0xb0, 0x2f, 0x3a, 0x82, 0x35,
	0xcd, 0x85, 0xd1, 0xb6, 0x74, 0xe7, 0x85, 0x4f, 0x6a, 0x0d, 0xe1, 0x39, 0xcd, 0x05, 0xf1, 0x60,
	0x7c, 0x4a, 0xc8, 0x3c, 0xa5, 0xc2, 0x78, 0x86, 0xc8, 0xab, 0x63, 0xe4, 0x77, 0x21, 0x91, 0x29,
	0xbc, 0x3e, 0x65, 0x70, 0x15, 0xc6, 0x73, 0x4b, 0x77, 0x34, 0x7f, 0x74, 0x0c, 0xe1, 0x22, 0xec,
	0xbf, 0xd0, 0xc1, 0x7c, 0x7e, 0x64, 0xb2, 0xb8, 0xd3, 0xef, 0x30, 0x54, 0x02, 0x62, 0x58, 0x3c,
	0x24, 0xf4, 0xf6, 0x91, 0x84, 0x4a, 0xda, 0x57, 0xc2, 0x2d, 0x2b, 0x76, 0x1f, 0xba, 0x8b, 0x7f,
	0x99, 0x5c, 0xb2, 0xff, 0x09, 0x86, 0x66, 0x0f, 0xa0, 0x57, 0x15, 0xca, 0x16, 0xef, 0xb6, 0x05,
	0xd0, 0x38, 0x91, 0x14, 0xda, 0x38, 0x10, 0xf9, 0xe0, 0x5e, 0xf4, 0x2c, 0xdd, 0xe6, 0x79, 0x99,
	0xde, 0x35, 0xc8, 0x61, 0xc2, 0x27, 0xe4, 0x46, 0x83, 0x51, 0x35, 0xd3, 0x37, 0xa5, 0x8d, 0x4c,
	0x2f, 0xb5, 0x53, 0xff, 0xd0, 0xfc, 0x78, 0x25, 0x55, 0xcd, 0x71, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x45, 0x65, 0xce, 0x44, 0xc0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuickstoreClient is the client API for Quickstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuickstoreClient interface {
	Store(ctx context.Context, in *StoreInput, opts ...grpc.CallOption) (*StoreOutput, error)
	ShutdownMicroservice(ctx context.Context, in *ShutdownInput, opts ...grpc.CallOption) (*ShutdownOutput, error)
}

type quickstoreClient struct {
	cc *grpc.ClientConn
}

func NewQuickstoreClient(cc *grpc.ClientConn) QuickstoreClient {
	return &quickstoreClient{cc}
}

func (c *quickstoreClient) Store(ctx context.Context, in *StoreInput, opts ...grpc.CallOption) (*StoreOutput, error) {
	out := new(StoreOutput)
	err := c.cc.Invoke(ctx, "/mako.internal.quickstore_microservice.Quickstore/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quickstoreClient) ShutdownMicroservice(ctx context.Context, in *ShutdownInput, opts ...grpc.CallOption) (*ShutdownOutput, error) {
	out := new(ShutdownOutput)
	err := c.cc.Invoke(ctx, "/mako.internal.quickstore_microservice.Quickstore/ShutdownMicroservice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuickstoreServer is the server API for Quickstore service.
type QuickstoreServer interface {
	Store(context.Context, *StoreInput) (*StoreOutput, error)
	ShutdownMicroservice(context.Context, *ShutdownInput) (*ShutdownOutput, error)
}

func RegisterQuickstoreServer(s *grpc.Server, srv QuickstoreServer) {
	s.RegisterService(&_Quickstore_serviceDesc, srv)
}

func _Quickstore_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickstoreServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mako.internal.quickstore_microservice.Quickstore/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickstoreServer).Store(ctx, req.(*StoreInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Quickstore_ShutdownMicroservice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuickstoreServer).ShutdownMicroservice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mako.internal.quickstore_microservice.Quickstore/ShutdownMicroservice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuickstoreServer).ShutdownMicroservice(ctx, req.(*ShutdownInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Quickstore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mako.internal.quickstore_microservice.Quickstore",
	HandlerType: (*QuickstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Quickstore_Store_Handler,
		},
		{
			MethodName: "ShutdownMicroservice",
			Handler:    _Quickstore_ShutdownMicroservice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/quickstore_microservice/proto/quickstore.proto",
}
