// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/internal/storage_client/storage.proto

package mako_internal

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	mako_go_proto "github.com/google/mako/spec/proto/mako_go_proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageRequestOptions struct {
	SudoRunAs            *string  `protobuf:"bytes,1,opt,name=sudo_run_as,json=sudoRunAs" json:"sudo_run_as,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageRequestOptions) Reset()         { *m = StorageRequestOptions{} }
func (m *StorageRequestOptions) String() string { return proto.CompactTextString(m) }
func (*StorageRequestOptions) ProtoMessage()    {}
func (*StorageRequestOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{0}
}

func (m *StorageRequestOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageRequestOptions.Unmarshal(m, b)
}
func (m *StorageRequestOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageRequestOptions.Marshal(b, m, deterministic)
}
func (m *StorageRequestOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageRequestOptions.Merge(m, src)
}
func (m *StorageRequestOptions) XXX_Size() int {
	return xxx_messageInfo_StorageRequestOptions.Size(m)
}
func (m *StorageRequestOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageRequestOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StorageRequestOptions proto.InternalMessageInfo

func (m *StorageRequestOptions) GetSudoRunAs() string {
	if m != nil && m.SudoRunAs != nil {
		return *m.SudoRunAs
	}
	return ""
}

type CreateProjectInfoRequest struct {
	Payload              *mako_go_proto.ProjectInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions     `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateProjectInfoRequest) Reset()         { *m = CreateProjectInfoRequest{} }
func (m *CreateProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectInfoRequest) ProtoMessage()    {}
func (*CreateProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{1}
}

func (m *CreateProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectInfoRequest.Unmarshal(m, b)
}
func (m *CreateProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectInfoRequest.Merge(m, src)
}
func (m *CreateProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectInfoRequest.Size(m)
}
func (m *CreateProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectInfoRequest proto.InternalMessageInfo

func (m *CreateProjectInfoRequest) GetPayload() *mako_go_proto.ProjectInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CreateProjectInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type UpdateProjectInfoRequest struct {
	Payload              *mako_go_proto.ProjectInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions     `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpdateProjectInfoRequest) Reset()         { *m = UpdateProjectInfoRequest{} }
func (m *UpdateProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectInfoRequest) ProtoMessage()    {}
func (*UpdateProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{2}
}

func (m *UpdateProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectInfoRequest.Unmarshal(m, b)
}
func (m *UpdateProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectInfoRequest.Merge(m, src)
}
func (m *UpdateProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectInfoRequest.Size(m)
}
func (m *UpdateProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectInfoRequest proto.InternalMessageInfo

func (m *UpdateProjectInfoRequest) GetPayload() *mako_go_proto.ProjectInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateProjectInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type GetProjectInfoRequest struct {
	Payload              *mako_go_proto.ProjectInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions     `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetProjectInfoRequest) Reset()         { *m = GetProjectInfoRequest{} }
func (m *GetProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetProjectInfoRequest) ProtoMessage()    {}
func (*GetProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{3}
}

func (m *GetProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectInfoRequest.Unmarshal(m, b)
}
func (m *GetProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectInfoRequest.Merge(m, src)
}
func (m *GetProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetProjectInfoRequest.Size(m)
}
func (m *GetProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectInfoRequest proto.InternalMessageInfo

func (m *GetProjectInfoRequest) GetPayload() *mako_go_proto.ProjectInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *GetProjectInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type ListProjectInfoRequest struct {
	Payload              *mako_go_proto.ProjectInfoQuery `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions          `protobuf:"bytes,1,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListProjectInfoRequest) Reset()         { *m = ListProjectInfoRequest{} }
func (m *ListProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectInfoRequest) ProtoMessage()    {}
func (*ListProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{4}
}

func (m *ListProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectInfoRequest.Unmarshal(m, b)
}
func (m *ListProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectInfoRequest.Merge(m, src)
}
func (m *ListProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectInfoRequest.Size(m)
}
func (m *ListProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectInfoRequest proto.InternalMessageInfo

func (m *ListProjectInfoRequest) GetPayload() *mako_go_proto.ProjectInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *ListProjectInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type QueryProjectInfoRequest struct {
	Payload              *mako_go_proto.ProjectInfoQuery `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions          `protobuf:"bytes,1,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *QueryProjectInfoRequest) Reset()         { *m = QueryProjectInfoRequest{} }
func (m *QueryProjectInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProjectInfoRequest) ProtoMessage()    {}
func (*QueryProjectInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{5}
}

func (m *QueryProjectInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProjectInfoRequest.Unmarshal(m, b)
}
func (m *QueryProjectInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProjectInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryProjectInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProjectInfoRequest.Merge(m, src)
}
func (m *QueryProjectInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryProjectInfoRequest.Size(m)
}
func (m *QueryProjectInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProjectInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProjectInfoRequest proto.InternalMessageInfo

func (m *QueryProjectInfoRequest) GetPayload() *mako_go_proto.ProjectInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *QueryProjectInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type CreateBenchmarkInfoRequest struct {
	Payload              *mako_go_proto.BenchmarkInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions       `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateBenchmarkInfoRequest) Reset()         { *m = CreateBenchmarkInfoRequest{} }
func (m *CreateBenchmarkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBenchmarkInfoRequest) ProtoMessage()    {}
func (*CreateBenchmarkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{6}
}

func (m *CreateBenchmarkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBenchmarkInfoRequest.Unmarshal(m, b)
}
func (m *CreateBenchmarkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBenchmarkInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateBenchmarkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBenchmarkInfoRequest.Merge(m, src)
}
func (m *CreateBenchmarkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBenchmarkInfoRequest.Size(m)
}
func (m *CreateBenchmarkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBenchmarkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBenchmarkInfoRequest proto.InternalMessageInfo

func (m *CreateBenchmarkInfoRequest) GetPayload() *mako_go_proto.BenchmarkInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CreateBenchmarkInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type UpdateBenchmarkInfoRequest struct {
	Payload              *mako_go_proto.BenchmarkInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions       `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UpdateBenchmarkInfoRequest) Reset()         { *m = UpdateBenchmarkInfoRequest{} }
func (m *UpdateBenchmarkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBenchmarkInfoRequest) ProtoMessage()    {}
func (*UpdateBenchmarkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{7}
}

func (m *UpdateBenchmarkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBenchmarkInfoRequest.Unmarshal(m, b)
}
func (m *UpdateBenchmarkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBenchmarkInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBenchmarkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBenchmarkInfoRequest.Merge(m, src)
}
func (m *UpdateBenchmarkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBenchmarkInfoRequest.Size(m)
}
func (m *UpdateBenchmarkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBenchmarkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBenchmarkInfoRequest proto.InternalMessageInfo

func (m *UpdateBenchmarkInfoRequest) GetPayload() *mako_go_proto.BenchmarkInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateBenchmarkInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type QueryBenchmarkInfoRequest struct {
	Payload              *mako_go_proto.BenchmarkInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions            `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *QueryBenchmarkInfoRequest) Reset()         { *m = QueryBenchmarkInfoRequest{} }
func (m *QueryBenchmarkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBenchmarkInfoRequest) ProtoMessage()    {}
func (*QueryBenchmarkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{8}
}

func (m *QueryBenchmarkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryBenchmarkInfoRequest.Unmarshal(m, b)
}
func (m *QueryBenchmarkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryBenchmarkInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryBenchmarkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBenchmarkInfoRequest.Merge(m, src)
}
func (m *QueryBenchmarkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryBenchmarkInfoRequest.Size(m)
}
func (m *QueryBenchmarkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBenchmarkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBenchmarkInfoRequest proto.InternalMessageInfo

func (m *QueryBenchmarkInfoRequest) GetPayload() *mako_go_proto.BenchmarkInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *QueryBenchmarkInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type DeleteBenchmarkInfoRequest struct {
	Payload              *mako_go_proto.BenchmarkInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions            `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *DeleteBenchmarkInfoRequest) Reset()         { *m = DeleteBenchmarkInfoRequest{} }
func (m *DeleteBenchmarkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBenchmarkInfoRequest) ProtoMessage()    {}
func (*DeleteBenchmarkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{9}
}

func (m *DeleteBenchmarkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBenchmarkInfoRequest.Unmarshal(m, b)
}
func (m *DeleteBenchmarkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBenchmarkInfoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBenchmarkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBenchmarkInfoRequest.Merge(m, src)
}
func (m *DeleteBenchmarkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBenchmarkInfoRequest.Size(m)
}
func (m *DeleteBenchmarkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBenchmarkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBenchmarkInfoRequest proto.InternalMessageInfo

func (m *DeleteBenchmarkInfoRequest) GetPayload() *mako_go_proto.BenchmarkInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DeleteBenchmarkInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type CountBenchmarkInfoRequest struct {
	Payload              *mako_go_proto.BenchmarkInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions            `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CountBenchmarkInfoRequest) Reset()         { *m = CountBenchmarkInfoRequest{} }
func (m *CountBenchmarkInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CountBenchmarkInfoRequest) ProtoMessage()    {}
func (*CountBenchmarkInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{10}
}

func (m *CountBenchmarkInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountBenchmarkInfoRequest.Unmarshal(m, b)
}
func (m *CountBenchmarkInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountBenchmarkInfoRequest.Marshal(b, m, deterministic)
}
func (m *CountBenchmarkInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountBenchmarkInfoRequest.Merge(m, src)
}
func (m *CountBenchmarkInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CountBenchmarkInfoRequest.Size(m)
}
func (m *CountBenchmarkInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountBenchmarkInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountBenchmarkInfoRequest proto.InternalMessageInfo

func (m *CountBenchmarkInfoRequest) GetPayload() *mako_go_proto.BenchmarkInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CountBenchmarkInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type CreateRunInfoRequest struct {
	Payload              *mako_go_proto.RunInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateRunInfoRequest) Reset()         { *m = CreateRunInfoRequest{} }
func (m *CreateRunInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRunInfoRequest) ProtoMessage()    {}
func (*CreateRunInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{11}
}

func (m *CreateRunInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRunInfoRequest.Unmarshal(m, b)
}
func (m *CreateRunInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRunInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateRunInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRunInfoRequest.Merge(m, src)
}
func (m *CreateRunInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRunInfoRequest.Size(m)
}
func (m *CreateRunInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRunInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRunInfoRequest proto.InternalMessageInfo

func (m *CreateRunInfoRequest) GetPayload() *mako_go_proto.RunInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CreateRunInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type UpdateRunInfoRequest struct {
	Payload              *mako_go_proto.RunInfo `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateRunInfoRequest) Reset()         { *m = UpdateRunInfoRequest{} }
func (m *UpdateRunInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRunInfoRequest) ProtoMessage()    {}
func (*UpdateRunInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{12}
}

func (m *UpdateRunInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRunInfoRequest.Unmarshal(m, b)
}
func (m *UpdateRunInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRunInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRunInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRunInfoRequest.Merge(m, src)
}
func (m *UpdateRunInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRunInfoRequest.Size(m)
}
func (m *UpdateRunInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRunInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRunInfoRequest proto.InternalMessageInfo

func (m *UpdateRunInfoRequest) GetPayload() *mako_go_proto.RunInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateRunInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type QueryRunInfoRequest struct {
	Payload              *mako_go_proto.RunInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions      `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *QueryRunInfoRequest) Reset()         { *m = QueryRunInfoRequest{} }
func (m *QueryRunInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRunInfoRequest) ProtoMessage()    {}
func (*QueryRunInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{13}
}

func (m *QueryRunInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRunInfoRequest.Unmarshal(m, b)
}
func (m *QueryRunInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRunInfoRequest.Marshal(b, m, deterministic)
}
func (m *QueryRunInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRunInfoRequest.Merge(m, src)
}
func (m *QueryRunInfoRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRunInfoRequest.Size(m)
}
func (m *QueryRunInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRunInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRunInfoRequest proto.InternalMessageInfo

func (m *QueryRunInfoRequest) GetPayload() *mako_go_proto.RunInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *QueryRunInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type DeleteRunInfoRequest struct {
	Payload              *mako_go_proto.RunInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions      `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DeleteRunInfoRequest) Reset()         { *m = DeleteRunInfoRequest{} }
func (m *DeleteRunInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRunInfoRequest) ProtoMessage()    {}
func (*DeleteRunInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{14}
}

func (m *DeleteRunInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRunInfoRequest.Unmarshal(m, b)
}
func (m *DeleteRunInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRunInfoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRunInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRunInfoRequest.Merge(m, src)
}
func (m *DeleteRunInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRunInfoRequest.Size(m)
}
func (m *DeleteRunInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRunInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRunInfoRequest proto.InternalMessageInfo

func (m *DeleteRunInfoRequest) GetPayload() *mako_go_proto.RunInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DeleteRunInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type CountRunInfoRequest struct {
	Payload              *mako_go_proto.RunInfoQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions      `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CountRunInfoRequest) Reset()         { *m = CountRunInfoRequest{} }
func (m *CountRunInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CountRunInfoRequest) ProtoMessage()    {}
func (*CountRunInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{15}
}

func (m *CountRunInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRunInfoRequest.Unmarshal(m, b)
}
func (m *CountRunInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRunInfoRequest.Marshal(b, m, deterministic)
}
func (m *CountRunInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRunInfoRequest.Merge(m, src)
}
func (m *CountRunInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CountRunInfoRequest.Size(m)
}
func (m *CountRunInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRunInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRunInfoRequest proto.InternalMessageInfo

func (m *CountRunInfoRequest) GetPayload() *mako_go_proto.RunInfoQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CountRunInfoRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type CreateSampleBatchRequest struct {
	Payload              *mako_go_proto.SampleBatch `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions     `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateSampleBatchRequest) Reset()         { *m = CreateSampleBatchRequest{} }
func (m *CreateSampleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSampleBatchRequest) ProtoMessage()    {}
func (*CreateSampleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{16}
}

func (m *CreateSampleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSampleBatchRequest.Unmarshal(m, b)
}
func (m *CreateSampleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSampleBatchRequest.Marshal(b, m, deterministic)
}
func (m *CreateSampleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSampleBatchRequest.Merge(m, src)
}
func (m *CreateSampleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSampleBatchRequest.Size(m)
}
func (m *CreateSampleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSampleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSampleBatchRequest proto.InternalMessageInfo

func (m *CreateSampleBatchRequest) GetPayload() *mako_go_proto.SampleBatch {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CreateSampleBatchRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type QuerySampleBatchRequest struct {
	Payload              *mako_go_proto.SampleBatchQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions          `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *QuerySampleBatchRequest) Reset()         { *m = QuerySampleBatchRequest{} }
func (m *QuerySampleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySampleBatchRequest) ProtoMessage()    {}
func (*QuerySampleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{17}
}

func (m *QuerySampleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuerySampleBatchRequest.Unmarshal(m, b)
}
func (m *QuerySampleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuerySampleBatchRequest.Marshal(b, m, deterministic)
}
func (m *QuerySampleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySampleBatchRequest.Merge(m, src)
}
func (m *QuerySampleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_QuerySampleBatchRequest.Size(m)
}
func (m *QuerySampleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySampleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySampleBatchRequest proto.InternalMessageInfo

func (m *QuerySampleBatchRequest) GetPayload() *mako_go_proto.SampleBatchQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *QuerySampleBatchRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

type DeleteSampleBatchRequest struct {
	Payload              *mako_go_proto.SampleBatchQuery `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	RequestOptions       *StorageRequestOptions          `protobuf:"bytes,2,opt,name=request_options,json=requestOptions" json:"request_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *DeleteSampleBatchRequest) Reset()         { *m = DeleteSampleBatchRequest{} }
func (m *DeleteSampleBatchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSampleBatchRequest) ProtoMessage()    {}
func (*DeleteSampleBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_323e51b363857a41, []int{18}
}

func (m *DeleteSampleBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSampleBatchRequest.Unmarshal(m, b)
}
func (m *DeleteSampleBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSampleBatchRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSampleBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSampleBatchRequest.Merge(m, src)
}
func (m *DeleteSampleBatchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSampleBatchRequest.Size(m)
}
func (m *DeleteSampleBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSampleBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSampleBatchRequest proto.InternalMessageInfo

func (m *DeleteSampleBatchRequest) GetPayload() *mako_go_proto.SampleBatchQuery {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *DeleteSampleBatchRequest) GetRequestOptions() *StorageRequestOptions {
	if m != nil {
		return m.RequestOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageRequestOptions)(nil), "mako.internal.StorageRequestOptions")
	proto.RegisterType((*CreateProjectInfoRequest)(nil), "mako.internal.CreateProjectInfoRequest")
	proto.RegisterType((*UpdateProjectInfoRequest)(nil), "mako.internal.UpdateProjectInfoRequest")
	proto.RegisterType((*GetProjectInfoRequest)(nil), "mako.internal.GetProjectInfoRequest")
	proto.RegisterType((*ListProjectInfoRequest)(nil), "mako.internal.ListProjectInfoRequest")
	proto.RegisterType((*QueryProjectInfoRequest)(nil), "mako.internal.QueryProjectInfoRequest")
	proto.RegisterType((*CreateBenchmarkInfoRequest)(nil), "mako.internal.CreateBenchmarkInfoRequest")
	proto.RegisterType((*UpdateBenchmarkInfoRequest)(nil), "mako.internal.UpdateBenchmarkInfoRequest")
	proto.RegisterType((*QueryBenchmarkInfoRequest)(nil), "mako.internal.QueryBenchmarkInfoRequest")
	proto.RegisterType((*DeleteBenchmarkInfoRequest)(nil), "mako.internal.DeleteBenchmarkInfoRequest")
	proto.RegisterType((*CountBenchmarkInfoRequest)(nil), "mako.internal.CountBenchmarkInfoRequest")
	proto.RegisterType((*CreateRunInfoRequest)(nil), "mako.internal.CreateRunInfoRequest")
	proto.RegisterType((*UpdateRunInfoRequest)(nil), "mako.internal.UpdateRunInfoRequest")
	proto.RegisterType((*QueryRunInfoRequest)(nil), "mako.internal.QueryRunInfoRequest")
	proto.RegisterType((*DeleteRunInfoRequest)(nil), "mako.internal.DeleteRunInfoRequest")
	proto.RegisterType((*CountRunInfoRequest)(nil), "mako.internal.CountRunInfoRequest")
	proto.RegisterType((*CreateSampleBatchRequest)(nil), "mako.internal.CreateSampleBatchRequest")
	proto.RegisterType((*QuerySampleBatchRequest)(nil), "mako.internal.QuerySampleBatchRequest")
	proto.RegisterType((*DeleteSampleBatchRequest)(nil), "mako.internal.DeleteSampleBatchRequest")
}

func init() {
	proto.RegisterFile("proto/internal/storage_client/storage.proto", fileDescriptor_323e51b363857a41)
}

var fileDescriptor_323e51b363857a41 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0xd6, 0xcf, 0x4b, 0xfb, 0x30,
	0x14, 0x00, 0x70, 0xf2, 0xbd, 0x7c, 0x59, 0xc6, 0x14, 0xbb, 0x1f, 0xd6, 0x1d, 0x44, 0x86, 0xa0,
	0x30, 0xed, 0xc6, 0x2e, 0x9e, 0xdd, 0x04, 0x11, 0x14, 0xb5, 0xc3, 0x73, 0x09, 0x5d, 0x74, 0x75,
	0x5d, 0x52, 0x93, 0xf4, 0xb0, 0x7f, 0xc2, 0x83, 0x03, 0x41, 0x05, 0xfd, 0x57, 0xa5, 0x89, 0x65,
	0x6d, 0x57, 0xdd, 0x61, 0x14, 0x72, 0x5b, 0xb7, 0x97, 0xbc, 0xcf, 0xde, 0xcb, 0x5b, 0x06, 0xdb,
	0x01, 0xa3, 0x82, 0x76, 0x3c, 0x22, 0x30, 0x23, 0xc8, 0xef, 0x70, 0x41, 0x19, 0x7a, 0xc0, 0x8e,
	0xeb, 0x7b, 0x98, 0x88, 0xf8, 0xd1, 0x92, 0x51, 0x46, 0x65, 0x8a, 0x26, 0xd4, 0x8a, 0x63, 0x9b,
	0x75, 0x1e, 0x60, 0xb7, 0xa3, 0x36, 0x90, 0x9f, 0xc8, 0x97, 0xad, 0x13, 0x58, 0x1f, 0xaa, 0x65,
	0x36, 0x7e, 0x0a, 0x31, 0x17, 0xd7, 0x81, 0xf0, 0x28, 0xe1, 0xc6, 0x2e, 0x2c, 0xf3, 0x70, 0x44,
	0x1d, 0x16, 0x12, 0x07, 0x71, 0x13, 0xec, 0x81, 0xc3, 0x92, 0x5d, 0x8a, 0xde, 0xb2, 0x43, 0x72,
	0xca, 0x5b, 0xaf, 0x00, 0x9a, 0x03, 0x86, 0x91, 0xc0, 0x37, 0x8c, 0x3e, 0x62, 0x57, 0x5c, 0x90,
	0x7b, 0xfa, 0xb3, 0x87, 0xd1, 0x86, 0xff, 0x03, 0x34, 0xf3, 0x29, 0x1a, 0xc9, 0x85, 0xe5, 0xde,
	0x96, 0x25, 0x73, 0x26, 0x43, 0xe3, 0x08, 0xe3, 0x0a, 0x6e, 0x32, 0xb5, 0xce, 0xa1, 0x2a, 0xb9,
	0xf9, 0x4f, 0x2e, 0xda, 0xb7, 0x52, 0x5f, 0xc1, 0xca, 0x85, 0xda, 0x1b, 0x2c, 0xf5, 0x2c, 0x61,
	0x77, 0xc1, 0x48, 0x3f, 0xd8, 0x1c, 0xc0, 0xfa, 0x39, 0x16, 0x9a, 0xa9, 0xde, 0x00, 0x6c, 0x5c,
	0x7a, 0x3c, 0x8f, 0xd5, 0x5d, 0xb0, 0x54, 0x86, 0xc6, 0x12, 0xeb, 0x36, 0xc4, 0x6c, 0xf6, 0xa7,
	0x0d, 0xac, 0x61, 0x7b, 0x07, 0x70, 0x5b, 0x66, 0xd0, 0x14, 0xd7, 0x54, 0x03, 0xd0, 0xc7, 0xc4,
	0x1d, 0x4f, 0x11, 0x9b, 0x24, 0x7d, 0xc7, 0xd9, 0x9e, 0x56, 0x55, 0x96, 0x74, 0x70, 0x51, 0x5d,
	0x8d, 0x70, 0x6a, 0x08, 0x34, 0xc4, 0x7d, 0x02, 0xb8, 0x23, 0x7b, 0x93, 0x6b, 0xeb, 0x65, 0x6d,
	0x66, 0x8e, 0x6d, 0x75, 0x6b, 0xd7, 0x01, 0x7e, 0x01, 0xd8, 0x3c, 0xc3, 0x3e, 0xfe, 0xa5, 0x7a,
	0x1a, 0x08, 0xa3, 0x12, 0x0e, 0x68, 0x48, 0x84, 0xae, 0xc0, 0x67, 0x00, 0x6b, 0x6a, 0x3a, 0xec,
	0x90, 0x24, 0x6d, 0x07, 0x59, 0x5b, 0x45, 0xed, 0x1f, 0x87, 0x15, 0x09, 0x52, 0x13, 0xa1, 0x09,
	0xe8, 0x05, 0xc0, 0xaa, 0xea, 0x41, 0xda, 0x73, 0x94, 0xf5, 0x18, 0x29, 0x4f, 0xb1, 0x6d, 0x9b,
	0x03, 0x58, 0x53, 0x27, 0x5f, 0x27, 0x55, 0x54, 0x2a, 0x79, 0xda, 0x75, 0x42, 0x2d, 0xfe, 0x00,
	0x0d, 0xd1, 0x34, 0xf0, 0x71, 0x1f, 0x09, 0x77, 0xbc, 0xea, 0x46, 0x4f, 0x86, 0x16, 0xf8, 0xdb,
	0xaf, 0x6e, 0xcd, 0x1c, 0x57, 0x37, 0xeb, 0x6a, 0x2c, 0xb9, 0x8a, 0xad, 0xda, 0x07, 0x80, 0xa6,
	0x3a, 0x60, 0x1a, 0xea, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xcd, 0xcc, 0x74, 0x61, 0x0b,
	0x00, 0x00,
}
