// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clients/proto/analyzers/threshold_analyzer.proto

package mako_analyzers_threshold_analyzer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	mako_go_proto "github.com/google/mako/spec/proto/mako_go_proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThresholdConfig struct {
	Min                  *float64                  `protobuf:"fixed64,1,opt,name=min" json:"min,omitempty"`
	Max                  *float64                  `protobuf:"fixed64,2,opt,name=max" json:"max,omitempty"`
	OutlierPercentMax    *float64                  `protobuf:"fixed64,3,opt,name=outlier_percent_max,json=outlierPercentMax" json:"outlier_percent_max,omitempty"`
	DataFilter           *mako_go_proto.DataFilter `protobuf:"bytes,4,opt,name=data_filter,json=dataFilter" json:"data_filter,omitempty"`
	ConfigName           *string                   `protobuf:"bytes,5,opt,name=config_name,json=configName" json:"config_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ThresholdConfig) Reset()         { *m = ThresholdConfig{} }
func (m *ThresholdConfig) String() string { return proto.CompactTextString(m) }
func (*ThresholdConfig) ProtoMessage()    {}
func (*ThresholdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc166777e6a25c0, []int{0}
}

func (m *ThresholdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdConfig.Unmarshal(m, b)
}
func (m *ThresholdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdConfig.Marshal(b, m, deterministic)
}
func (m *ThresholdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdConfig.Merge(m, src)
}
func (m *ThresholdConfig) XXX_Size() int {
	return xxx_messageInfo_ThresholdConfig.Size(m)
}
func (m *ThresholdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdConfig proto.InternalMessageInfo

func (m *ThresholdConfig) GetMin() float64 {
	if m != nil && m.Min != nil {
		return *m.Min
	}
	return 0
}

func (m *ThresholdConfig) GetMax() float64 {
	if m != nil && m.Max != nil {
		return *m.Max
	}
	return 0
}

func (m *ThresholdConfig) GetOutlierPercentMax() float64 {
	if m != nil && m.OutlierPercentMax != nil {
		return *m.OutlierPercentMax
	}
	return 0
}

func (m *ThresholdConfig) GetDataFilter() *mako_go_proto.DataFilter {
	if m != nil {
		return m.DataFilter
	}
	return nil
}

func (m *ThresholdConfig) GetConfigName() string {
	if m != nil && m.ConfigName != nil {
		return *m.ConfigName
	}
	return ""
}

type ThresholdAnalyzerInput struct {
	Configs              []*ThresholdConfig `protobuf:"bytes,1,rep,name=configs" json:"configs,omitempty"`
	Name                 *string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThresholdAnalyzerInput) Reset()         { *m = ThresholdAnalyzerInput{} }
func (m *ThresholdAnalyzerInput) String() string { return proto.CompactTextString(m) }
func (*ThresholdAnalyzerInput) ProtoMessage()    {}
func (*ThresholdAnalyzerInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc166777e6a25c0, []int{1}
}

func (m *ThresholdAnalyzerInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdAnalyzerInput.Unmarshal(m, b)
}
func (m *ThresholdAnalyzerInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdAnalyzerInput.Marshal(b, m, deterministic)
}
func (m *ThresholdAnalyzerInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdAnalyzerInput.Merge(m, src)
}
func (m *ThresholdAnalyzerInput) XXX_Size() int {
	return xxx_messageInfo_ThresholdAnalyzerInput.Size(m)
}
func (m *ThresholdAnalyzerInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdAnalyzerInput.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdAnalyzerInput proto.InternalMessageInfo

func (m *ThresholdAnalyzerInput) GetConfigs() []*ThresholdConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

func (m *ThresholdAnalyzerInput) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ThresholdAnalyzerOutput struct {
	ConfigResults        []*ThresholdConfigResult `protobuf:"bytes,1,rep,name=config_results,json=configResults" json:"config_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ThresholdAnalyzerOutput) Reset()         { *m = ThresholdAnalyzerOutput{} }
func (m *ThresholdAnalyzerOutput) String() string { return proto.CompactTextString(m) }
func (*ThresholdAnalyzerOutput) ProtoMessage()    {}
func (*ThresholdAnalyzerOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc166777e6a25c0, []int{2}
}

func (m *ThresholdAnalyzerOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdAnalyzerOutput.Unmarshal(m, b)
}
func (m *ThresholdAnalyzerOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdAnalyzerOutput.Marshal(b, m, deterministic)
}
func (m *ThresholdAnalyzerOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdAnalyzerOutput.Merge(m, src)
}
func (m *ThresholdAnalyzerOutput) XXX_Size() int {
	return xxx_messageInfo_ThresholdAnalyzerOutput.Size(m)
}
func (m *ThresholdAnalyzerOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdAnalyzerOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdAnalyzerOutput proto.InternalMessageInfo

func (m *ThresholdAnalyzerOutput) GetConfigResults() []*ThresholdConfigResult {
	if m != nil {
		return m.ConfigResults
	}
	return nil
}

type ThresholdConfigResult struct {
	PercentAboveMax       *float64         `protobuf:"fixed64,1,opt,name=percent_above_max,json=percentAboveMax" json:"percent_above_max,omitempty"`
	PercentBelowMin       *float64         `protobuf:"fixed64,2,opt,name=percent_below_min,json=percentBelowMin" json:"percent_below_min,omitempty"`
	ValueOutsideThreshold *float64         `protobuf:"fixed64,3,opt,name=value_outside_threshold,json=valueOutsideThreshold" json:"value_outside_threshold,omitempty"`
	MetricLabel           *string          `protobuf:"bytes,4,opt,name=metric_label,json=metricLabel" json:"metric_label,omitempty"`
	Config                *ThresholdConfig `protobuf:"bytes,5,opt,name=config" json:"config,omitempty"`
	Regression            *bool            `protobuf:"varint,6,opt,name=regression" json:"regression,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *ThresholdConfigResult) Reset()         { *m = ThresholdConfigResult{} }
func (m *ThresholdConfigResult) String() string { return proto.CompactTextString(m) }
func (*ThresholdConfigResult) ProtoMessage()    {}
func (*ThresholdConfigResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc166777e6a25c0, []int{3}
}

func (m *ThresholdConfigResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdConfigResult.Unmarshal(m, b)
}
func (m *ThresholdConfigResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdConfigResult.Marshal(b, m, deterministic)
}
func (m *ThresholdConfigResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdConfigResult.Merge(m, src)
}
func (m *ThresholdConfigResult) XXX_Size() int {
	return xxx_messageInfo_ThresholdConfigResult.Size(m)
}
func (m *ThresholdConfigResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdConfigResult.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdConfigResult proto.InternalMessageInfo

func (m *ThresholdConfigResult) GetPercentAboveMax() float64 {
	if m != nil && m.PercentAboveMax != nil {
		return *m.PercentAboveMax
	}
	return 0
}

func (m *ThresholdConfigResult) GetPercentBelowMin() float64 {
	if m != nil && m.PercentBelowMin != nil {
		return *m.PercentBelowMin
	}
	return 0
}

func (m *ThresholdConfigResult) GetValueOutsideThreshold() float64 {
	if m != nil && m.ValueOutsideThreshold != nil {
		return *m.ValueOutsideThreshold
	}
	return 0
}

func (m *ThresholdConfigResult) GetMetricLabel() string {
	if m != nil && m.MetricLabel != nil {
		return *m.MetricLabel
	}
	return ""
}

func (m *ThresholdConfigResult) GetConfig() *ThresholdConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ThresholdConfigResult) GetRegression() bool {
	if m != nil && m.Regression != nil {
		return *m.Regression
	}
	return false
}

func init() {
	proto.RegisterType((*ThresholdConfig)(nil), "mako.analyzers.threshold_analyzer.ThresholdConfig")
	proto.RegisterType((*ThresholdAnalyzerInput)(nil), "mako.analyzers.threshold_analyzer.ThresholdAnalyzerInput")
	proto.RegisterType((*ThresholdAnalyzerOutput)(nil), "mako.analyzers.threshold_analyzer.ThresholdAnalyzerOutput")
	proto.RegisterType((*ThresholdConfigResult)(nil), "mako.analyzers.threshold_analyzer.ThresholdConfigResult")
}

func init() {
	proto.RegisterFile("clients/proto/analyzers/threshold_analyzer.proto", fileDescriptor_efc166777e6a25c0)
}

var fileDescriptor_efc166777e6a25c0 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x76, 0x0c, 0xf6, 0x02, 0x6c, 0x33, 0x2a, 0x8b, 0x38, 0x40, 0xd6, 0x53, 0xc4,
	0x21, 0x85, 0x1e, 0x10, 0xd7, 0x01, 0x42, 0x02, 0x6d, 0x0c, 0x45, 0xdc, 0x2d, 0x37, 0x7d, 0xdb,
	0x2c, 0x1c, 0xbb, 0xb2, 0x9d, 0x51, 0xfa, 0x87, 0x21, 0xf1, 0xdf, 0x21, 0xbf, 0x38, 0x51, 0x61,
	0x48, 0x93, 0x76, 0x7b, 0xfe, 0xbe, 0x9f, 0x9e, 0x3f, 0xfb, 0x83, 0x57, 0xb5, 0x92, 0xa8, 0xbd,
	0x9b, 0xad, 0xac, 0xf1, 0x66, 0x26, 0xb4, 0x50, 0x3f, 0x37, 0x68, 0xdd, 0xcc, 0x5f, 0x59, 0x74,
	0x57, 0x46, 0x2d, 0x79, 0xaf, 0x95, 0x84, 0xb0, 0xe3, 0x46, 0x7c, 0x37, 0xe5, 0x00, 0x96, 0x37,
	0xc1, 0x67, 0x13, 0xb7, 0xc2, 0x3a, 0x6e, 0x24, 0x9a, 0xc6, 0xe9, 0xef, 0x04, 0xf6, 0xbf, 0xf5,
	0xf4, 0x7b, 0xa3, 0x2f, 0xe4, 0x25, 0x3b, 0x80, 0x71, 0x23, 0x75, 0x96, 0xe4, 0x49, 0x91, 0x54,
	0x61, 0x24, 0x45, 0xac, 0xb3, 0x51, 0x54, 0xc4, 0x9a, 0x95, 0xf0, 0xc4, 0xb4, 0x5e, 0x49, 0xb4,
	0x7c, 0x85, 0xb6, 0x46, 0xed, 0x79, 0x20, 0xc6, 0x44, 0x1c, 0x46, 0xeb, 0x6b, 0xe7, 0x9c, 0x89,
	0x35, 0x7b, 0x0d, 0xe9, 0x52, 0x78, 0xc1, 0x2f, 0xa4, 0xf2, 0x68, 0xb3, 0x9d, 0x3c, 0x29, 0xd2,
	0xf9, 0x41, 0x49, 0x49, 0x3e, 0x08, 0x2f, 0x3e, 0x92, 0x5e, 0xc1, 0x72, 0x98, 0xd9, 0x0b, 0x48,
	0x6b, 0x0a, 0xc4, 0xb5, 0x68, 0x30, 0xbb, 0x97, 0x27, 0xc5, 0x5e, 0x05, 0x9d, 0xf4, 0x45, 0x34,
	0x38, 0xdd, 0xc0, 0xd3, 0x21, 0xfa, 0x49, 0x7c, 0xe7, 0x27, 0xbd, 0x6a, 0x3d, 0x3b, 0x85, 0xfb,
	0x1d, 0xe7, 0xb2, 0x24, 0x1f, 0x17, 0xe9, 0x7c, 0x5e, 0xde, 0xfa, 0x43, 0xe5, 0x3f, 0xdf, 0x50,
	0xf5, 0x2b, 0x18, 0x83, 0x1d, 0x4a, 0x30, 0xa2, 0x04, 0x34, 0x4f, 0x37, 0x70, 0x74, 0xe3, 0xee,
	0xf3, 0xd6, 0x87, 0xcb, 0x39, 0x3c, 0x8e, 0xb9, 0x2d, 0xba, 0x56, 0xf9, 0x3e, 0xc3, 0xdb, 0x3b,
	0x64, 0xa0, 0x05, 0xd5, 0xa3, 0x7a, 0xeb, 0xe4, 0xa6, 0xbf, 0x46, 0x30, 0xf9, 0x2f, 0xc8, 0x5e,
	0xc2, 0x61, 0xdf, 0x86, 0x58, 0x98, 0x6b, 0xa4, 0x4e, 0xba, 0x1e, 0xf7, 0xa3, 0x71, 0x12, 0xf4,
	0xd0, 0xc8, 0x16, 0xbb, 0x40, 0x65, 0x7e, 0xf0, 0xd0, 0xf9, 0xe8, 0x2f, 0xf6, 0x5d, 0xd0, 0xcf,
	0xa4, 0x66, 0x6f, 0xe0, 0xe8, 0x5a, 0xa8, 0x16, 0xb9, 0x69, 0xbd, 0x93, 0x4b, 0xe4, 0x43, 0xf4,
	0xd8, 0xf8, 0x84, 0xec, 0xf3, 0xce, 0x1d, 0xb2, 0xb1, 0x63, 0x78, 0xd8, 0xa0, 0xb7, 0xb2, 0xe6,
	0x4a, 0x2c, 0x50, 0x51, 0xed, 0x7b, 0x55, 0xda, 0x69, 0xa7, 0x41, 0x62, 0x9f, 0x61, 0xb7, 0x7b,
	0x1d, 0x15, 0x7c, 0xb7, 0xa6, 0xe2, 0x06, 0xf6, 0x1c, 0xc0, 0xe2, 0xa5, 0x45, 0xe7, 0xa4, 0xd1,
	0xd9, 0x6e, 0x9e, 0x14, 0x0f, 0xaa, 0x2d, 0xe5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xc0,
	0xc0, 0xfb, 0x59, 0x03, 0x00, 0x00,
}
